### ISSUE TITLE
text-decoration-underline in notes.htm

### ISSUE THREAD

**Issue by gabru-md** [nsITians/nsITians.github.io#1]
navigation bar shows line under the tabs.

Only in notes.htm
Please do : text-decoration : none;

- gabru-md

**Comment by lakshay365** [comment]
Removing Bootstrap will fix this. This is not needed as we are going to revamp the page entirely. You can close this issue

**Comment by gabru-md** [comment]
okay cool. let me remove the bootstrap dependency first.
you take care of the /notes instead of /notes.htm thing in index.htm.

**Comment by gabru-md** [comment]
Issue resolved. Hence closed.

**Comment by gabru-md** [comment]
the issue is resolved now and can be viewed at: <a href="https://nsitians.github.io/notes.htm">https://nsitians.github.io/notes.htm</a>
